import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
await page.goto("http://localhost:3456/", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/new-1-journal.png" });
await page.locator(".ink-intake").click();
await page.waitForTimeout(1200);
await page.screenshot({ path: "/tmp/new-2-digest.png" });
await browser.close();
console.log("done");
